name: Build APK
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Dar permisos a gradlew
        run: chmod +x ./gradlew

      - name: Compilar APK (Debug)
        run: ./gradlew assembleDebug

      - name: Subir APK como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: FloraLens-APK
          path: app/build/outputs/apk/debug/app-debug.apk
